name: starterpack_deploy
channels:
    - default
    - pytorch
    - anconda
dependencies:
    - python=3.8
    - pip
    - pytorch
    - torchvision
    - cudatoolkit=10.1
    - flask
    - scipy
    - pip:
        - jupyter