name: deploy_cv
channels:
    - default
    - pytorch
    - anaconda
dependencies:
    - python=3.8
    - pip
    - pytorch
    - torchvision
    - cudatoolkit=10.1
    - flask
    - scipy
    - gunicorn