name: deploy_cv
channels:
    - default
    - pytorch
    - anaconda
    - conda-forge
dependencies:
    - python=3.8
    - pip
    - pytorch
    - torchvision
    - cuda100
    - cudnn
    - flask
    - scipy
    - gunicorn
    - opencv
    - seaborn
    - tqdm